"""cart model added

Revision ID: 922a4d0ccab7
Revises: 
Create Date: 2026-05-14 21:13:13.023448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922a4d0ccab7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('pack_size', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('cart_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_bestseller', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.String(), nullable=True))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'tags')
    op.drop_column('products', 'is_bestseller')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'cart_count')
    op.drop_column('products', 'view_count')
    op.drop_column('products', 'pack_size')
    op.drop_column('products', 'cost_price')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
