"""support model

Revision ID: b6b664aa27d4
Revises: 5f4f64cfd4fa
Create Date: 2026-06-17 17:15:11.842626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b664aa27d4'
down_revision: Union[str, Sequence[str], None] = '5f4f64cfd4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
