"""add image_url to support messages

Revision ID: c3e8f9a2b1d7
Revises: b6b664aa27d4
Create Date: 2026-06-19 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e8f9a2b1d7'
down_revision: Union[str, Sequence[str], None] = 'b6b664aa27d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_messages', 'image_url')
    # ### end Alembic commands ###
