"""intial commit

Revision ID: eb28b5c4c842
Revises: 
Create Date: 2026-05-12 16:50:57.846727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb28b5c4c842'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
